name = "Glaciare"
author = "AIGO Team, which means Verbina29, mostly."
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "118d45b394077d1007c390540c961c5ec765e0909eb4369d030c943a13f7c975"

[versions]
forge = "47.1.5"
minecraft = "1.20.1"
