name = "Glaciare"
author = "AIGO Team, which means Verbina29, mostly."
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96450324576e430150daf30ac78ce72d455128439dd2543b3fa969c7f8d5da3c"

[versions]
forge = "47.1.5"
minecraft = "1.20.1"
