name = "Glaciare"
author = "AIGO Team, which means Verbina29, mostly."
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9657ba0c9b0f4de6cee6afa30facb5fd311eba315e354d5639fc7f07f0e15c19"

[versions]
forge = "47.1.5"
minecraft = "1.20.1"
