name = "Glaciare"
author = "AIGO Team, which means Verbina29, mostly."
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e48b8673b3ab12c5230e4a750c5941e66edcc455c7e6d67d910796df5945b22b"

[versions]
forge = "47.1.5"
minecraft = "1.20.1"
