name = "Glaciare"
author = "AIGO Team, which means Verbina29, mostly."
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1f791a3a532fd546415e6bc3c85826d532dd920c3feb4aba0df9a8a3a50f64f"

[versions]
forge = "47.1.5"
minecraft = "1.20.1"
