name = "Glaciare"
author = "AIGO Team, which means Verbina29, mostly."
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "129d6cd7566dfcd4724d854f12f93bddd262211b3de29c378113958e4ea75e58"

[versions]
forge = "47.1.5"
minecraft = "1.20.1"
