name = "Glaciare"
author = "AIGO Team, which means Verbina29, mostly."
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b03c5d46eff54d426c6862b90f5e421ba6ad1f4af3953685429f58061108a913"

[versions]
forge = "47.1.5"
minecraft = "1.20.1"
