name = "Glaciare"
author = "AIGO Team, which means Verbina29, mostly."
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3529e6e8a581a4cbc1cdeaf1d52b4457436a4ce29dd379a8bfa7242a3535d471"

[versions]
forge = "47.1.5"
minecraft = "1.20.1"
