name = "Glaciare"
author = "AIGO Team, which means Verbina29, mostly."
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d29a7f43397ba9fd1cf01f873486775a11104a2883b8fa50882d91ddfe3ef57f"

[versions]
forge = "47.1.5"
minecraft = "1.20.1"
