name = "Glaciare"
author = "AIGO Team, which means Verbina29, mostly."
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38d5ef5dbe1af846f5978410597e581a4703787cb58687f845e29406828af7b1"

[versions]
forge = "47.1.5"
minecraft = "1.20.1"
