name = "Glaciare"
author = "AIGO Team, which means Verbina29, mostly."
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40fcb39553ff2fde5b3535569c310d208b894adaeb676b85faac24f7f1059691"

[versions]
forge = "47.1.5"
minecraft = "1.20.1"
