name = "Glaciare"
author = "AIGO Team, which means Verbina29, mostly."
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32c5e4a40de5c75e71ab3cb69a929beaad0f4abc84feb7c5c19ddb93f8a43f2e"

[versions]
forge = "47.1.5"
minecraft = "1.20.1"
