name = "Glaciare"
author = "AIGO Team, which means Verbina29, mostly."
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c9a69042e6af07c1b022e3a9b1d089a94d8a7456d89292e169cd6afb5a7b210"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
