name = "Glaciare"
author = "AIGO Team, which means Verbina29, mostly."
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4205f097fe34cd86d0150eda98f004e9205c023bbbd8845373ce8e0119b8c73"

[versions]
forge = "47.1.5"
minecraft = "1.20.1"
