name = "Glaciare"
author = "AIGO Team, which means Verbina29, mostly."
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77eaf9e4f37ed635e3d9078e28d7daa0e54daa1a534bd7e8cf9399553dd5dd71"

[versions]
forge = "47.1.5"
minecraft = "1.20.1"
