name = "Glaciare"
author = "AIGO Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca78a47b2e987e5ad05481fc82753ed2e14b921b49c0af0109f21bbf68c71f70"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.97"
