name = "Glaciare"
author = "AIGO Team, which means Verbina29, mostly."
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f183d13ea2ac223c91d257810819ce4eae16fe3e1732015643db153b2328a96"

[versions]
forge = "47.1.5"
minecraft = "1.20.1"
