name = "Glaciare"
author = "AIGO Team, which means Verbina29, mostly."
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2c7ccac7bfd5138284b1a21b7710a07d688d1eb123686939b3ca39577dd6fbf"

[versions]
forge = "47.1.5"
minecraft = "1.20.1"
